# Site settings
title: Extent Clothing
email: extentclothing@gmail.com
description: "BMX Clothing brand based in central PA. Established in 2004."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: extentbrand
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
